version: '3.8'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - better-erc20-watcher-network

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - better-erc20-watcher-network

  react-app:
      image: better-erc20-watcher/react-app:latest
      restart: always
      ports:
        - "80:3000"
      networks:
        - better-erc20-watcher-network

  api-gateway:
    image: better-erc20-watcher/api-gateway:latest
    restart: always
    networks:
      - better-erc20-watcher-network

  tx-ingestion-engine:
    image: better-erc20-watcher/tx-ingestion-engine:latest
    restart: always
    networks:
      - better-erc20-watcher-network

  labeling-engine:
    image: better-erc20-watcher/labeling-engine:latest
    restart: always
    networks:
      - better-erc20-watcher-network

  master-rate-limiter:
    image: better-erc20-watcher/master-rate-limiter:latest
    restart: always
    networks:
      - better-erc20-watcher-network

  token-external-lookup:
    image: better-erc20-watcher/token-external-lookup:latest
    restart: always
    networks:
      - better-erc20-watcher-network

networks:
  better-erc20-watcher-network:
    driver: bridge
