version: '3'

services:
  zookeeper:
    image: ubuntu/zookeeper
    ports:
      - "2181:2181"
    networks:
        - better-erc20-watcher-network
        
  kafka:
    image: ubuntu/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
        - better-erc20-watcher-network
          
  kafka-manager:
    image: kafkamanager/kafka-manager
    environment:
      ZK_HOSTS: zookeeper
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    restart: always
    networks:
      - better-erc20-watcher-network

networks:
  better-erc20-watcher-network:
    name: better-erc20-watcher-network
    driver: bridge
